
server:
  port: 8084


spring:
  application:
    name: booking-service
#provide cloud config uri
  config:
    import: configserver:http://localhost:8888
##datasource specific properties
#  datasource:
#    username: root
#    password: abcd
#    url: jdbc:mysql://localhost:3306/msmoviedb
##jpa properties
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
eureka:
 client:
   service-url:
     default-zone: http://eureka-server 
management:
   endpoints:
     web:
       exposure:
         include: "*"
   endpoint:
     health:
       show-details: always
     circuitbreakers:
       enabled: true
   health:
     circuitbreakers:
       enabled: true
resilience4j:
  circuitbreaker:
   instances:
    cart-cbservice:
     sliding-window-type: COUNT_BASED
     failure-rate-threshold: 50
     minimum-number-of-calls: 5
     automatic-transition-from-open-to-half-open-enabled: true
     wait-duration-in-open-state: 5s
     permitted-number-of-calls-in-half-open-state: 3
     sliding-window-size: 10
     register-health-indicator: true
     record-exceptions:
       - java.lang.Exception	 
